### ISSUE TITLE
Opening OData source gives Unrecognized type Edm.GeographyPoint

### ISSUE THREAD

**Issue by peterodk** [simplefx/Simple.OData#2]
When opening this datasource the error "Unrecognized type Edm.GeographyPoint" is thrown.

url="http://services.odata.org/V3/OData/OData.svc/";
dynamic db = Database.Opener.Open(url);
table="Products";
IEnumerable data= db[table].All();

**Comment by object** [comment]
Thank you for the bug report. I've extended type definitions with geometry/geography types, so this error should not occur (get Simple.Data.OData version 0.13.1). However, the actual use of these types in client code requires more implementation work, I will create a separate issue for this.

**Comment by peterodk** [comment]
Thank you so much for fixing it so fast!
