### ISSUE TITLE
Request fails when $metadata is append to the URL and doesn't exist on source

### ISSUE THREAD

**Issue by peterodk** [simplefx/Simple.OData#4]
http://dynamics01:7048/DynamicsNAV70/OData/Company('CRONUS%20International%20Ltd.')/$metadata

Source of data at root of service:
  <?xml version="1.0" encoding="utf-8" standalone="yes" ?> 
 <entry xml:base="http://dynamics01:7048/DynamicsNAV70/OData/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
  <id>http://dynamics01:7048/DynamicsNAV70/OData/Company('CRONUS%20International%20Ltd.')</id> 
  <title type="text" /> 
  <updated>2013-05-16T19:21:54Z</updated> 
 <author>
  <name /> 
  </author>
  <link rel="edit" title="Company" href="Company('CRONUS%20International%20Ltd.')" /> 
  <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/TestData" type="application/atom+xml;type=feed" title="TestData" href="Company('CRONUS%20International%20Ltd.')/TestData" /> 
  <category term="NAV.Company" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /> 
 <content type="application/xml">
 <m:properties>
  <d:Name>CRONUS International Ltd./d:Name 
  /m:properties
  </content>
  </entry>

Datasource that must be accessed:

Url:
http://dynamics01:7048/DynamicsNAV70/OData/Company('CRONUS%20International%20Ltd.')/TestData

<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>
<feed xml:base="http://dynamics01:7048/DynamicsNAV70/OData/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
  <title type="text">TestData</title>
  <id>http://dynamics01:7048/DynamicsNAV70/OData/Company('CRONUS%20International%20Ltd.')/TestData</id>
  <updated>2013-05-16T18:48:12Z</updated>
  <link rel="self" title="TestData" href="TestData" />
  <entry>
    <id>http://dynamics01:7048/DynamicsNAV70/OData/TestData('01121212')</id>
    <title type="text"></title>
    <updated>2013-05-16T18:48:12Z</updated>
    <author>
      <name />
    </author>
    <link rel="edit" title="TestData" href="TestData('01121212')" />
    <category term="NAV.TestData" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
    <content type="application/xml">
      <m:properties>
        <d:Customer_No>01121212/d:Customer_No
        <d:Sum_Sales_LCY m:type="Edm.Decimal">0/d:Sum_Sales_LCY
        <d:Sum_Profit_LCY m:type="Edm.Decimal">0/d:Sum_Profit_LCY
        <d:User_ID_FilterOnly m:null="true" />
        <d:Date_Filter_FilterOnly m:type="Edm.DateTime" m:null="true" />
      /m:properties
    </content>
  </entry>
  <entry>
    <id>http://dynamics01:7048/DynamicsNAV70/OData/TestData('10000')</id>
    <title type="text"></title>
    <updated>2013-05-16T18:48:12Z</updated>
    <author>
      <name />
    </author>
    <link rel="edit" title="TestData" href="TestData('10000')" />
    <category term="NAV.TestData" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
    <content type="application/xml">
      <m:properties>
        <d:Customer_No>10000/d:Customer_No
        <d:Sum_Sales_LCY m:type="Edm.Decimal">17100.96/d:Sum_Sales_LCY
        <d:Sum_Profit_LCY m:type="Edm.Decimal">5338.26/d:Sum_Profit_LCY
        <d:User_ID_FilterOnly m:null="true" />
        <d:Date_Filter_FilterOnly m:type="Edm.DateTime" m:null="true" />
      /m:properties
    </content>
  </entry>
  <entry>
    <id>http://dynamics01:7048/DynamicsNAV70/OData/TestData('20000')</id>
    <title type="text"></title>
    <updated>2013-05-16T18:48:12Z</updated>
    <author>
      <name />
    </author>
    <link rel="edit" title="TestData" href="TestData('20000')" />
    <category term="NAV.TestData" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
    <content type="application/xml">
      <m:properties>
        <d:Customer_No>20000/d:Customer_No
        <d:Sum_Sales_LCY m:type="Edm.Decimal">6510.64/d:Sum_Sales_LCY
        <d:Sum_Profit_LCY m:type="Edm.Decimal">2511.94/d:Sum_Profit_LCY
        <d:User_ID_FilterOnly m:null="true" />
        <d:Date_Filter_FilterOnly m:type="Edm.DateTime" m:null="true" />
      /m:properties
    </content>
  </entry>
  <entry>
    <id>http://dynamics01:7048/DynamicsNAV70/OData/TestData('30000')</id>
    <title type="text"></title>
    <updated>2013-05-16T18:48:12Z</updated>
    <author>
      <name />
    </author>
    <link rel="edit" title="TestData" href="TestData('30000')" />
    <category term="NAV.TestData" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
    <content type="application/xml">
      <m:properties>
        <d:Customer_No>30000/d:Customer_No
        <d:Sum_Sales_LCY m:type="Edm.Decimal">6142.9/d:Sum_Sales_LCY
        <d:Sum_Profit_LCY m:type="Edm.Decimal">2921/d:Sum_Profit_LCY
        <d:User_ID_FilterOnly m:null="true" />
        <d:Date_Filter_FilterOnly m:type="Edm.DateTime" m:null="true" />
      /m:properties
    </content>
  </entry>
</feed>

**Comment by peterodk** [comment]
Well .... apparently github isn't too happy about XML ....

**Comment by peterodk** [comment]
Data can be found here:
https://dl.dropboxusercontent.com/u/85638338/NAV2013%20source/SimpleOdataIssue.zip

**Comment by object** [comment]
Hi,
I saw you just closed this issue. Wan't it a problem with Simple.OData?

**Comment by peterodk** [comment]
Hi Vagif

I found an issue with the Dynamics NAV and authentication, apparenty there’s an issue with handling the authentication with Windows NTLM/Kerberos authentication.

Right now I’m looking at using RSSBus OData as a replacement as I got that component to connect, but honestly I would rather get your component working as it game me what I need for my project ;-)

I actually sent an email to Mark Rendle and asked for you email since I’m very interested in getting it to work, however I never heard back from him (therefore RSSBus came into play).

Best Regards

[cid:image001.jpg@01CE6358.B28CD910]

Peter Ørum
Product Manager
Phone:

+1 813 933 4600

Mobile:

+1 813 514 5892

Fax:

+1 813 315 6511

E-mail:

po@targit.com mailto:po@targit.com

Website:

www.targit.comhttp://www.targit.com/

[cid:image002.png@01CE6358.B28CD910]http://twitter.com/TARGIT [cid:image003.png@01CE6358.B28CD910] http://www.facebook.com/TARGIT.BI.Suite  [cid:image004.png@01CE6358.B28CD910] http://www.linkedin.com/company/targit  [cid:image005.png@01CE6358.B28CD910] http://plus.google.com/b/110275487177355569658/110275487177355569658/posts  [cid:image006.png@01CE6358.B28CD910] http://www.targit.com/YouTARGIT  [cid:image007.jpg@01CE6358.B28CD910] http://www.youtube.com/user/TargitAS
This message may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.

**Comment by object** [comment]
Hello Peter,
You can contact me directly at vagif.abilov at gmail.com. I have only one week before 2 weeks vacation,so it's a question what I can do in a short time. But if this seems as Simple.OData issue and I am able to reproduce it, I will try to get it fixed.

**Comment by peterodk** [comment]
Sounds great ;-) Thank you very much Vagif!

Best Regards

[cid:image001.jpg@01CE6367.F191D250]

Peter Ørum
Product Manager
Phone:

+1 813 933 4600

Mobile:

+1 813 514 5892

Fax:

+1 813 315 6511

E-mail:

po@targit.com mailto:po@targit.com

Website:

www.targit.comhttp://www.targit.com/

[cid:image002.png@01CE6367.F191D250]http://twitter.com/TARGIT [cid:image003.png@01CE6367.F191D250] http://www.facebook.com/TARGIT.BI.Suite  [cid:image004.png@01CE6367.F191D250] http://www.linkedin.com/company/targit  [cid:image005.png@01CE6367.F191D250] http://plus.google.com/b/110275487177355569658/110275487177355569658/posts  [cid:image006.png@01CE6367.F191D250] http://www.targit.com/YouTARGIT  [cid:image007.jpg@01CE6367.F191D250] http://www.youtube.com/user/TargitAS
This message may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.
