### ISSUE TITLE
Incorrect handling of Nullable

### ISSUE THREAD

**Issue by richardod** [simplefx/Simple.OData#5]
If you use the Northwind OData example, you will find that the ReportsTo property returns nullable as False in your library, when in fact it is true. The code should be changed so that if the Nullable attribute is missing, it defaults to true as per this spec:

http://www.odata.org/documentation/odata-v3-documentation/common-schema-definition-language-csdl/#531_The_edmNullable_Attribute

**Comment by object** [comment]
Thank you, working on this one.

**Comment by object** [comment]
Fixed in Simple.OData.Client, will be released in v.0.16.1.
